### ISSUE TITLE
Does not support latest render manager [2.4]

### ISSUE THREAD

**Issue by jackjt8** [leMaik/chunky-discord#1]
```
Plugin chunky-discord.jar failed to load.
java.lang.NoSuchMethodError: 'se.llbit.chunky.renderer.Renderer se.llbit.chunky.renderer.RenderController.getRenderer()'
	at de.lemaik.chunky.discord.DiscordPlugin.attach(DiscordPlugin.java:52)
	at se.llbit.chunky.main.Chunky.lambda$loadPlugins$5(Chunky.java:269)
	at se.llbit.chunky.plugin.ChunkyPlugin.load(ChunkyPlugin.java:90)
	at se.llbit.chunky.main.Chunky.loadPlugins(Chunky.java:259)
	at se.llbit.chunky.main.Chunky.main(Chunky.java:213)
```

**Comment by leMaik** [comment]
Closed by https://github.com/leMaik/chunky-discord/commit/33c726c1eb9ccdc99ff0725d271dbebaedfd1e88
